# -*- coding: utf-8 -*-
"""Artistas por tema y créditos, desde la descripción de YouTube. Sin red.

La hoja ponía el nombre del canal como artista de todos los temas y marcaba
compositores y editoriales como imposibles de obtener. Las descripciones reales
de los Art Tracks traen las dos cosas: «Título · Artista · Invitado» y líneas
como «Composer, Lyricist: Nombre». En los datos reales, 46 de 50 temas traían
compositor. Cubre:

  - qué artistas y qué créditos se leen, y cuáles no
  - que la hoja los use, y que lo que falta siga a completar
  - el aviso cuando el artista del canal no es el principal del tema
"""

import csv
import io

from conftest import _producto, _track
from migrador import paquete as pq
from migrador import relevar_core as R
from migrador import validar as V

DESC = """Provided to YouTube by Sello Chico

Tema Nuevo (feat. Invitada) · Fulano · Invitada

Disco Nuevo

℗ 2021 Sello Chico

Released on: 2021-06-01

Producer, Composer: Fulano Pérez
Composer, Lyricist: Invitada Gómez
Mixing  Engineer: Alguien Que No Va
Associated Performer, Vocal: Invitada
Music  Publisher: Editorial Chica
Writer: Otro Autor

Auto-generated by YouTube."""


def test_se_leen_los_artistas_en_orden():
    assert R.parse_description(DESC)["artists"] == ["Fulano", "Invitada"]


def test_se_leen_los_creditos_que_pide_la_ingesta_y_nada_mas():
    c = R.parse_description(DESC)["credits"]
    assert c["composers"] == ["Fulano Pérez", "Invitada Gómez", "Otro Autor"]
    assert c["lyricists"] == ["Invitada Gómez"]
    assert c["producers"] == ["Fulano Pérez"]
    # «Music  Publisher», con los dos espacios que escribe YouTube.
    assert c["publishers"] == ["Editorial Chica"]
    todos = c["composers"] + c["lyricists"] + c["producers"] + c["publishers"]
    assert "Alguien Que No Va" not in todos and "Invitada" not in todos


def test_writer_no_es_letrista():
    """En un instrumental no hay letra: ponerlo como letrista sería afirmar
    algo que la fuente no dice."""
    c = R.parse_description("Provided to YouTube by X\n\nTema · A\n\n℗ 2001 X\n\nWriter: Alguien")["credits"]
    assert c["composers"] == ["Alguien"] and c["lyricists"] == []


def test_sin_creditos_ni_artistas_no_se_inventa_nada():
    r = R.parse_description("Provided to YouTube by X\n\nTema suelto\n\n℗ 2001 X")
    assert r["artists"] == []
    assert not any(r["credits"].values())


def _track_con(artists=None, credits=None):
    t = _track("Tema Nuevo (feat. Invitada)", album="Disco", year=2021)
    if artists is not None:
        t["artists"] = artists
    if credits is not None:
        t["credits"] = credits
    return t


def _fila(t, artista="Fulano"):
    p = _producto(title="Disco", tracks=[t])
    return next(csv.DictReader(io.StringIO(pq.hoja_ingesta_csv([p], artista))))


def test_la_hoja_usa_artistas_y_creditos():
    meta = R.parse_description(DESC)
    fila = _fila(_track_con(artists=meta["artists"], credits=meta["credits"]))
    assert fila["Track Artist"] == "Fulano"
    assert fila["Additional Artists"] == "Invitada"
    assert fila["Composer"] == "Fulano Pérez; Invitada Gómez; Otro Autor"
    assert fila["Lyricist"] == "Invitada Gómez"
    assert fila["Producer"] == "Fulano Pérez"
    assert fila["Publisher"] == "Editorial Chica"


def test_sin_datos_la_hoja_sigue_como_antes():
    fila = _fila(_track_con())
    assert fila["Track Artist"] == "Fulano"
    assert fila["Additional Artists"] == ""
    for columna in ("Composer", "Lyricist", "Producer", "Publisher"):
        assert fila[columna] == pq.MARCA_COMPLETAR


def test_otro_artista_principal_se_avisa():
    p = _producto(title="Compilado", tracks=[_track_con(artists=["Otra Banda", "Fulano"])])
    p["artist"] = "Fulano"
    avisos = [h for h in V.validar([p])["hallazgos"] if h["codigo"] == "artista_no_principal"]
    assert [h["nivel"] for h in avisos] == ["aviso"]
    assert "Otra Banda" in avisos[0]["mensaje"]


def test_el_mismo_artista_escrito_distinto_no_es_otro():
    p = _producto(title="Disco", tracks=[_track_con(artists=["FULANO"])])
    p["artist"] = "Fulano"
    assert "artista_no_principal" not in [h["codigo"] for h in V.validar([p])["hallazgos"]]
