# -*- coding: utf-8 -*-
"""La fecha de lanzamiento. Sin red.

La hoja de ingesta ponía como «Release Date» la fecha en que se subió el video a
YouTube, y si no había, un 1 de enero armado con el año. En las descripciones
reales de los Art Tracks, un tema de 2001 figura subido en 2024: el release
migrado salía con una fecha de hace un año. La fecha real está en la
descripción, en «Released on:». Cubre:

  - que se lea la fecha entera, y que una imposible no pase
  - que la fecha de lanzamiento y la de subida viajen por separado
  - que la hoja lleve la real, o <<COMPLETAR>>, y nunca la de subida
"""

import csv
import io

import pytest

from conftest import _track
from migrador import paquete as pq
from migrador import productos as pr
from migrador import relevar_core as R

DESC = (
    "Provided to YouTube by Sello Chico\n\n"
    "Tema Viejo · Artista\n\n"
    "Disco Viejo\n\n"
    "℗ 2001 Sello Chico\n\n"
    "Released on: 2001-05-14\n\n"
    "Composer: Alguien\n\n"
    "Auto-generated by YouTube."
)


def test_se_lee_la_fecha_completa():
    r = R.parse_description(DESC)
    assert r["release_date"] == "2001-05-14"
    assert r["release_year"] == 2001


@pytest.mark.parametrize(
    "linea, esperado",
    [
        ("Released on: 2023-13-45", None),  # imposible
        ("Released on: 1850-01-01", None),  # no plausible
        ("Released on: 2023-02-29", None),  # 2023 no es bisiesto
        ("Released on: 2024-02-29", "2024-02-29"),
        ("", None),
    ],
)
def test_una_fecha_imposible_no_es_un_dato(linea, esperado):
    desc = f"Provided to YouTube by X\n\nTema · A\n\n℗ 2023\n\n{linea}"
    assert R.parse_description(desc)["release_date"] == esperado


def test_la_fecha_de_subida_no_se_confunde_con_la_de_lanzamiento():
    video = {
        "id": "abc",
        "snippet": {"title": "Tema Viejo", "description": DESC, "publishedAt": "2024-12-12T10:02:58Z"},
        "statistics": {"viewCount": "10"},
        "contentDetails": {"duration": "PT3M20S"},
    }
    t = R.build_tracks([video])[0]
    assert t["upload_date"] == "2024-12-12"
    assert t["release_date"] == "2001-05-14"


def test_el_producto_toma_la_fecha_real_y_guarda_aparte_la_de_subida():
    tracks = [
        _track("Uno", album="Disco", year=2001, date="2024-12-12", released="2001-05-14", vid="a"),
        _track("Dos", album="Disco", year=2001, date="2024-12-11", released="2001-05-14", vid="b"),
    ]
    p = pr.group_products(tracks)[0]
    assert p["release_date"] == "2001-05-14"
    assert p["upload_date"] == "2024-12-11"


def test_sin_released_on_el_producto_no_tiene_fecha():
    p = pr.group_products([_track("Suelto", year=2019, date="2020-03-03", vid="a")])[0]
    assert p["release_date"] == ""
    assert p["upload_date"] == "2020-03-03"


def _fechas_de_la_hoja(productos):
    filas = list(csv.DictReader(io.StringIO(pq.hoja_ingesta_csv(productos, "Artista"))))
    return [(f["Release Date"], f["Original Release Date"]) for f in filas]


def test_la_hoja_lleva_la_fecha_real_en_las_dos_columnas():
    tracks = [_track("Uno", album="Disco", year=2001, date="2024-12-12", released="2001-05-14", vid="a")]
    assert _fechas_de_la_hoja(pr.group_products(tracks)) == [("2001-05-14", "2001-05-14")]


def test_sin_fecha_real_la_hoja_pide_completarla_y_no_inventa_el_1_de_enero():
    tracks = [_track("Suelto", year=2019, date="2020-03-03", vid="a")]
    fechas = _fechas_de_la_hoja(pr.group_products(tracks))
    assert fechas == [(pq.MARCA_COMPLETAR, pq.MARCA_COMPLETAR)]


def test_los_filtros_por_fecha_miran_la_subida():
    """El filtro de la interfaz habla de cuándo se publicó en YouTube, y así
    sigue: cambió el nombre del campo, no lo que filtra."""
    ps = pr.group_products([_track("Suelto", year=2001, date="2020-03-03", released="2001-01-01", vid="a")])
    assert pr.filter_products(ps, date_from="2020-01-01", date_to="2020-12-31") == ps
    assert pr.filter_products(ps, date_from="2001-01-01", date_to="2001-12-31") == []
