# -*- coding: utf-8 -*-
"""Parseo de las descripciones auto-generadas de YouTube. Sin red.

Cubre las reglas frágiles de `relevar_core.parse_description`.
  - línea ℗ con año pero SIN sello, captura el año y deja el sello en None
  - línea ℗ con año y sello, captura los dos
  - single o EP, donde el tercer bloque es la línea ℗ y no un álbum
  - respaldo por «Released on:» para el año cuando el ℗ no lo trae
  - descripción vacía, que devuelve un dict con todo en None
"""

import pytest

from migrador.relevar_core import parse_description as parse


def test_phono_con_anio_y_sin_sello():
    """El año se captura igual. El sello queda en None, no se inventa."""
    r = parse("Provided to YouTube by DistroKid\n\nMi Cancion · Artista\n\n℗ 2023")
    assert r["release_year"] == 2023
    assert r["label"] is None


def test_phono_con_espacio_al_final():
    r = parse("Provided to YouTube by DistroKid\n\nMi Cancion · Artista\n\n℗ 2023 ")
    assert r["release_year"] == 2023
    assert r["label"] is None


def test_phono_con_anio_y_sello_y_bloque_de_album():
    r = parse("Provided to YouTube by DistroKid\n\nMi Cancion · Artista\n\nAlbum X\n\n℗ 2023 Sello Indie\n")
    assert r["release_year"] == 2023
    assert r["label"] == "Sello Indie"
    assert r["album"] == "Album X"


def test_si_el_tercer_bloque_es_la_linea_phono_no_hay_album():
    r = parse(
        "Provided to YouTube by DistroKid\n\nMi Cancion · Artista\n\n"
        "℗ 2023 Sello Indie\n\nReleased on: 2023-05-01\n"
    )
    assert r["album"] is None
    assert r["release_year"] == 2023
    assert r["label"] == "Sello Indie"


def test_single_sin_cuarto_bloque():
    r = parse("Provided to YouTube by ONErpm\n\nTema · Artista\n\n℗ 2024 Algun Sello")
    assert r["album"] is None
    assert r["release_year"] == 2024


def test_si_el_tercer_bloque_es_released_on_tampoco_hay_album():
    r = parse("Provided to YouTube by DistroKid\n\nTema · Artista\n\nReleased on: 2022-01-01\n\n℗ 2022")
    assert r["album"] is None
    assert r["release_year"] == 2022


def test_released_on_es_el_respaldo_para_el_anio():
    r = parse("Provided to YouTube by DistroKid\n\nTema · Artista\n\nReleased on: 2021-03-03")
    assert r["release_year"] == 2021


# ============================================================
# El sello numérico de DistroKid no es un año
# ============================================================
#
# Caso real, encontrado usando la app sobre un catálogo de verdad. DistroKid
# escribe "℗ 5358533 Records DK" cuando el artista no cargó ningún sello, y ese
# número es el id de su cuenta. El parseo agarraba los primeros cuatro dígitos y
# publicaba "año 5358" en los cuatro productos del catálogo.


def test_el_relleno_de_distrokid_no_se_toma_como_anio_ni_como_sello():
    r = parse(
        "Provided to YouTube by DistroKid\n\n"
        "Cama De Dos Plazas · Santicuado.Q · Joaco Lynch\n\n"
        "Breathless\n\n"
        "℗ 5358533 Records DK\n\n"
        "Released on: 2026-09-11\n\n"
        "Auto-generated by YouTube."
    )
    assert r["release_year"] == 2026  # sale de "Released on:", no del ℗
    assert r["label"] is None
    assert r["album"] == "Breathless"
    assert r["distributor"] == "DistroKid"


def test_sin_released_on_el_anio_queda_vacio_en_vez_de_inventado():
    """Vacío lo marca la app como aviso. Un número inventado se publica."""
    r = parse("Provided to YouTube by DistroKid\n\nT · A\n\nDisco\n\n℗ 5358533 Records DK")
    assert r["release_year"] is None
    assert r["label"] is None


@pytest.mark.parametrize(
    "linea, anio, sello",
    [
        ("℗ 1203 Algo", None, "1203 Algo"),  # imposible, la línea entera es sello
        ("℗ 2199 Sello", None, "2199 Sello"),  # futuro lejano, es un error de carga
        ("℗ 2023 Cerro Bayo", 2023, "Cerro Bayo"),
    ],
)
def test_solo_pasan_los_anios_plausibles(linea, anio, sello):
    r = parse(f"Provided to YouTube by X\n\nT · A\n\nDisco\n\n{linea}")
    assert r["release_year"] == anio
    assert r["label"] == sello


def test_descripcion_vacia():
    assert parse("") == {"distributor": None, "album": None, "release_year": None, "label": None}
